# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2021-11-10 08:11
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('crm', '0023_user_field_is_mandatory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_notify', models.PositiveIntegerField(choices=[(0, 'More than a week has passed since the last lesson')], verbose_name='Type of notification')),
                ('is_sent', models.BooleanField(default=False, verbose_name='Is sent')),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=dict, verbose_name='Data')),
                ('count_attempts', models.PositiveIntegerField(default=0, verbose_name='Count of attempts')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='crm.Customer', verbose_name='Receiver')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
            },
        ),
    ]
